# Generated by Django 2.2.7 on 2020-08-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homedetails',
            table='HomeDetails',
        ),
    ]
